# Generated by Django 4.1.1 on 2022-09-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_post_author_delete_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="website", new_name="url",
        ),
    ]
